### ISSUE TITLE
star imports do not work for external/system modules

### ISSUE THREAD

**Issue by zauberparacelsus** [MyWorldLLC/Chipmunk#18] opened 2020-12-06 17:48 UTC
Star imports do not work for external modules or for system modules, only for modules within the same file.

So, the following will fail:
`import chipmunk.math.*`

**Comment by danielperano** [comment] 2020-12-06 18:00
One quick note about imports - unlike Python, Chipmunk doesn't allow importing a module as an object, so the statement `import chipmunk.math` will try to import the symbol `math` from the module `chipmunk`. To import all symbols from the module you'd use `import chipmunk.math.*`.

**Comment by danielperano** [comment] 2020-12-06 18:00
Does it still fail if you use the star import form?

**Comment by zauberparacelsus** [comment] 2020-12-06 18:02
The initial report meant to include a *, but I made a typo.  Correcting...

**Comment by zauberparacelsus** [comment] 2020-12-06 18:04
Oh, and apparently `import chipmunk.math` doesn't work either.  It gives the following error:
```chipmunk.compiler.UnresolvedSymbolException: math is not defined or imported in module chipmunk```

I'm guessing that system or external imports are just not working in general.

**Comment by danielperano** [comment] 2020-12-06 18:08
Yeah, `import chipmunk.math` will never work unless there's a module named `chipmunk` that contains the symbol `math`.

System imports do work for importing single symbols (I.e, `import chipmunk.math.sin`), but the star imports are definitely broken.

(In this early version of the CLI, as you've found it's only able to find modules defined in the same script file. This is because the CLI does not yet have a search path for resolving non-system modules outside of the script. It's a deficiency, but expected behavior at the moment.)

**Comment by danielperano** [comment] 2020-12-08 07:56
Fixed by 39ceda7.

**Closed by danielperano** 2020-12-08 07:56 UTC
Labels: bug
